addfriend/urls.py
from django.conf.urls import url
from .views import index, message_post, message_table

urlpatterns = [
	url(r'^add_message', message_post, name='add_message'),		
    url(r'^result_table', message_table, name='result_table'),
    url(r'^$', index, name='index'),
]

statistic/urls.py
from django.conf.urls import url
from .views import statistic_count

urlpatterns = [
    url(r'^$', statistic_count, name='statistic_count'),
]

tp01Kelompok02PPW/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls import url,include
from django.contrib import admin

import ustatus.urls as ustatus
import addfriend.urls as addfriend
import upprofile.urls as upprofile
import statistic.urls as statistic

urlpatterns = [
    url(r'^$', RedirectView.as_view(permanent='True', url = 'ustatus/')),
    url(r'^admin/', admin.site.urls),
    url(r'^add-friend/', include(addfriend,namespace='add-friend')),
    url(r'^ustatus/', include(ustatus,namespace='ustatus')),
    url(r'^upprofil/', include(upprofile, namespace='upprofile')),
    url(r'^statistic/', include(statistic, namespace='statistic')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

upprofile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    ]

ustatus/urls.py
from django.conf.urls import url
from .views import index,submit

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^submit/', submit, name='submit'),
    ]

addfriend/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    name = models.CharField(max_length=30)
    link = models.EmailField()
    created_date = models.DateTimeField(auto_now_add=True)

statistic/models.py
from django.db import models

# Create your models here.

upprofile/models.py
from django.db import models

# Create your models here.
class descriptoin(models.Model):
    nama = "KELOMPOK 2"
    birthday = "01 Jan"
    gender = "female"
    expertise = "Marketing, Collector, Public Speaking"
    description = "Antique expert. Experience as marketer for 10 years"
    email = "hello@smith.com"
    

ustatus/models.py
from django.db import models

# Create your models here.
class Status (models.Model):
    text = models.CharField(max_length=140)
    created_date = models.DateTimeField(auto_now_add=True)

addfriend/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan link',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=True, max_length=27, empty_value='Unknown', widget=forms.TextInput(attrs=attrs))
    link = forms.URLField(required=True, widget=forms.URLInput(attrs=attrs), empty_value='unknown.herokuapp.com')

ustatus/forms.py
from django import forms

class Form_Status(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    status_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':"What's going on...",
        'cols': 100,
        'rows': 4,
    }

    text = forms.CharField(label='', required=True, max_length=140, widget=forms.TextInput(attrs=status_attrs))

addfriend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message
# Create your views here.

response = {}

def index(request):
    message = Message.objects.all()
    response['message'] = message
    html = 'addfriend.html'
    return render(request, html, response)

def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['link'] = request.POST['link'] if request.POST['link'] != "" else "Anonymous"
        message = Message(name=response['name'], link=response['link'])
        message.save()
        html ='addfriend.html'
        return HttpResponseRedirect('/add-friend/')
    else:  
        return HttpResponseRedirect('/add-friend/')

def message_table(request):
    message = Message.objects.all()
    response['message'] = message
    html = 'addfriend.html'
    return render(request, html , response)

statistic/views.py
from django.shortcuts import render
from addfriend.models import Message
from ustatus.models import Status

response = {'author' : "Kelompok 2"}

# Create your views here.
def statistic_count(request):
	count_friend = Message.objects.all().count()
	response['count_friend'] = count_friend
	count_post = Status.objects.all().count()
	response['count_post'] = count_post


	html = 'statistic/statistic.html'
	qs = Status.objects.order_by('-created_date')
	if(len(qs) > 0):
		latest_post = qs[0]
	else:
		latest_post = None
	response['latest_post'] = latest_post
	
	return render(request, html, response) 

upprofile/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from templates.UserData import author, name
from datetime import datetime, date

birthday = date(2017,1,1)
gender = 'female'
expertise = 'Marketing, Collector, Public Speaking'
description = 'Antique expert. Experience as marketer for 10 years'
email = 'hello@smith.com'


content = [
{'subject' : 'Birthday' , 'value' : birthday.strftime('%d %B')},\
{'subject' : 'Gender' , 'value' : gender},\
{'subject' : 'Expertise' , 'value' : expertise},\
{'subject' : 'Description' , 'value' : description},\
{'subject' : 'Email' , 'value' : email},
]
# Create your views here.

def index(request):
    #TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
    html = 'upprofile/upprofile.html'
    response = {'author' : author, 'name' : name, 'content' : content, 'expertise' : expertise}
    return render(request, html, response)

ustatus/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Form_Status
from .models import Status
from templates.UserData import author, name

# Create your views here.
response={}
def index(request):
    status = Status.objects.all()
    response["nama"]=name
    response['form_status'] = Form_Status
    response['status']=status
    return render(request,'ustatus.html',response)
def submit(request):
    response['text'] = request.POST['text']
    status = Status(text=response['text'],)
    status.save()
    return HttpResponseRedirect('/ustatus/')

addfriend/templates/addfriend.html
{% extends "layout/base.html" %}
{% block content %}

<section name="form">
    <h2>Add Friend</h2>
    <form id="form" method="POST" action="{% url 'add-friend:add_message' %}">
        <label for="id_name"    >Nama: </label>
        <input id="id_name" class="form-control" name="name" placeholder="Joseph" type="text">
        <label for="id_email">Link: </label>
        <input id="id_email" class="form-control" name="link" placeholder="joseph.herokuapp.com" type="link">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Add Friend</button>
    </form>
</section>
</font>

<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">Friend List</h2>
        <div class="flex">
        <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
        {% for i in message %}
        {% if i.name == 'Anonymous' or i.link == 'Anonymous' %}
        <tr class="warning"> {% else %} <tr class="success">
            {% endif %}
            <div class="flex-item">
                        <div class="to-do-list">
                            <div class="to-do-list-title">
                                {{i.name}}
                            </div>
                            <div class="to-do-list-date-added">
                                {{i.created_date.date}} {{i.created_date.time}}
                            </div>
                            <div class="to-do-list-description">
                                <a href="http://{{i.link}}/" > {{i.link}} </a>
                            </div>
                        </div>
            </div>
        </tr>             
        {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

addfriend/templates/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description" content="Add Friend">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/addfriend.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/statistic.css' %}" />
    <title> 
        {% block title %} Add Friends{% endblock %}
    </title>
</head>
<body>
    <header>
        {% include "statistic/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "statistic/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

addfriend/templates/partials/footer.html
<p>&copy; Kelompok 2 PPW</p>

addfriend/templates/partials/header.html
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="">Aji Wuryanto - Arkthusk</a> -->
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="/ustatus"> Status </a></li>
        <li><a href="/upprofile"> Profile </a></li>
        <li><a href="{% url 'add-friend:index' %}#form"> Friends </a></li>
        <li><a href="{% url 'statistic:statistic_count' %}#form"> Stats </a></li>


      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

statistic/templates/statistic/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Lingin">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/statistic.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nosifer" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Crete+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sigmar+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Concert+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Aclonica" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ultra" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Racing+Sans+One" rel="stylesheet">

    <title>
        {% block title %} Lingin {% endblock %}
    </title>
</head>
<body style = 'background-image: url(http://www.powerpointhintergrund.com/uploads/2017/07/light-pink-background-light-pink-backgrounds-light-pink-gradient--29.jpeg)'>

    <header>
        {% include "statistic/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "statistic/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>

</body>
</html>

statistic/templates/statistic/partials/footer.html
 <p>&copy; {{author}}</p>

statistic/templates/statistic/partials/header.html
<!-- templates/update_status/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Ling In</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- LINK MENUJU Status, Profile, Friends, dan Stats  -->
        <li class="nav-item">
          <a class="nav-link" href="/ustatus">Status</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/upprofil">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/add-friend">Friends</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/statistic">Stats</a>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav> 

statistic/templates/statistic/statistic.html
    {% extends "statistic/layout/base.html" %}
    {% load staticfiles %}
    {% load static %}
    
    
    {% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/statistic.css' %}">
    
    <h1 style = "font-family: 'Crete Round', serif; margin-left:60px; margin-bottom:30px"> Statistic </h1>
    <style type="text/css">
        
    </style>
    <div class = 'flex-container'>
        <div class = 'row'>
            <div class = 'column' style = 'align :left'>

               <img width = '200' height = '200' src= "http://i0.kym-cdn.com/photos/images/original/000/437/036/b64.png" style = "border-left:0px; float: middle;margin-left: 40%">
             </div>

            <div class = 'column'>
                <h1 style = "font-family: 'Sigmar One', cursive; float: middle; margin-top: 25%">KELOMPOK 2</h1>
            </div>
        </div>
        <div class = 'row'>
            <h1 style = "font-family: 'Sigmar One';margin-left: 13%">~~~~~~~~~~~~~~~~~~~~~~~</h1>
        </div>
        <div class = 'row'>
            <div class = 'column'>
                <p style = "font-family: 'Aclonica', sans-serif; margin-left:50%;margin-top:15%"><b> FRIENDS </b></p>
                <p style = "margin-left:55% ;font-size: 30px"> {{ count_friend }} </p>
            </div>
            <div class = 'column'>
                <p style = "font-family: 'Aclonica', sans-serif; margin-left:50%;margin-top:15%"><b> FEED </b></p>
                <p style = "margin-left:53% ;font-size: 30px"> {{ count_post }} </p>
            </div>
        </div>
        <div class = 'row'>
            <div class = 'column'>
                <p style = "font-family: 'Ultra', serif; margin-top:15%; margin-left:51%;margin bottom:10%" ;><b> LATEST POST </b></p>
            </div>
            <div class = 'row'>
                <p style = "font-family: 'Racing Sans One', cursive; margin-top:3.6%;margin-left:23% ;font-size: 30px;margin bottom:10%"> {{ last_post }} </p>
            </div>
        </div>
    <br></br>
    </div>
    {% endblock %}

templates/footer.html
<p>&copy; {{author}}</p>

templates/header.html
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'statistic:index' %}">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="{% url 'statistic:index' %}#form"> Form </a></li>
        </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

upprofile/templates/upprofile/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="PROFILE PAGE">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        {% block title %} Profile Page By {{author}}{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "upprofile/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "upprofile/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

upprofile/templates/upprofile/upprofile.html
{% extends "statistic/layout/base.html" %}

    {% block content %}

    {% load staticfiles %}
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/upprofile.css' %}">
    
    <h1>Profile</h1>
    <style type="text/css">
        .image{
            border-radius: 50%;
            width: 200px;
            height: 200px;
            margin-left: 40%;
        }
    </style>
    <img class = "image" src= "http://i0.kym-cdn.com/photos/images/original/000/437/036/b64.png">
    <center><h1>KELOMPOK 2</h1></center>
    <br></br>
        <table align="center">
        {% for i in content %}
            <tr>
                <td class="subject" style="text-align: left; padding-left: 10px; padding-right:20px; padding-bottom: 20px">{{i.subject}}</td>
                <td class="value" style="text-align: left; padding-left: 10px; padding-right:20px; padding-bottom: 20px">{{ i.value }}</td>
            </tr>
        {% endfor %}
        </table>
        <br></br>
    
    {% endblock %}

ustatus/templates/ustatus.html
{% extends "statistic/layout/base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}
<div class="container" style="background-color: light-blue;;border-color:grey">
<div><center>
  <h1>UPDATE STATUS</h1><br>
  <form id="form" method="POST" action="/submit/">
      {% csrf_token %}
      {{ form_status }}
      <input id="submit" type="submit" class="btn btn-sm btn-default " style="" value="Post">
      <br>
  </form>
</center>
</div>

<div style="margin-left:10%;margin-right:10%">
  <div class="flex">

    {% if status %}
      {% for data in status reversed%}
      <div class="flex-item">
        <a href="/upprofile/"><img height="50" weight="5  0" class="img-circle" src = "http://i0.kym-cdn.com/photos/images/original/000/437/036/b64.png"></a>
        <a href="/upprofile/"><div><h4>{{ nama }}</h4></div></a>
        {{data.text}} <br> on {{data.created_date}}
      </div>

      {% endfor %}
    {% endif %}
  </div>

</div>
</div>
</div>

{% endblock %}